/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package POO;

import javax.swing.DefaultListModel;

/**
 *
 * @author HECTOR MAURICIO
 */
public class frmCotizador extends javax.swing.JFrame {

    //Declarar la lista de destinos
    private ListaCotizacion lista;
    
    /**
     * Creates new form frmCotizador
     */
    public frmCotizador() {
        initComponents();
        jcbDestinoTuristico.addItem("Puesto Vallarta");
        jcbDestinoTuristico.addItem("Mazamitla");
        jcbDestinoTuristico.addItem("Zihuatanejo");
        jcbDestinoTuristico.addItem("Manzanillo");
        jcbDestinoTuristico.addItem("Cancun");
        limpiar();

        
        //Inicializar lista
        lista = new ListaCotizacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfCantidadDias = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbDestinoTuristico = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbTarjeta = new javax.swing.JCheckBox();
        jcbMensualidad = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlsHabitacion = new javax.swing.JList();
        jbnRegresar = new javax.swing.JButton();
        jbnRegistrar = new javax.swing.JButton();
        jbnMostrar = new javax.swing.JButton();
        jbnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cotización ");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Usuario");

        jLabel3.setText("Cantidad de dias");

        jLabel4.setText("Destino Turistico");

        jcbDestinoTuristico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDestinoTuristicoActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo de habitacion");

        jLabel6.setText("Tipo de pago");

        jcbTarjeta.setText("Tarjeta");
        jcbTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTarjetaActionPerformed(evt);
            }
        });

        jcbMensualidad.setText("Mensualidades");

        jLabel7.setText("IVA");

        jLabel8.setText("16%");

        jLabel9.setText("Total a pagar");

        jLabel10.setText("jLabel10");

        jScrollPane1.setViewportView(jlsHabitacion);

        jScrollPane2.setViewportView(jScrollPane1);

        jbnRegresar.setText("Regresar");

        jbnRegistrar.setText("Registrar");
        jbnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnRegistrarActionPerformed(evt);
            }
        });

        jbnMostrar.setText("Mostrar");
        jbnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnMostrarActionPerformed(evt);
            }
        });

        jbnLimpiar.setText("Limpiar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbnRegresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                                .addComponent(jbnRegistrar)
                                .addGap(84, 84, 84)
                                .addComponent(jbnMostrar)
                                .addGap(95, 95, 95)
                                .addComponent(jbnLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtfCantidadDias, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                                            .addComponent(jtfUsuario)
                                            .addComponent(jcbDestinoTuristico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(jcbTarjeta)
                                                .addGap(26, 26, 26)
                                                .addComponent(jcbMensualidad))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCantidadDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbDestinoTuristico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbTarjeta)
                    .addComponent(jcbMensualidad))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnRegresar)
                    .addComponent(jbnRegistrar)
                    .addComponent(jbnMostrar)
                    .addComponent(jbnLimpiar))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbDestinoTuristicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDestinoTuristicoActionPerformed
        //Crear el modelo para agregar a componente Jlist
        DefaultListModel modelo = new DefaultListModel();
        switch(jcbDestinoTuristico.getSelectedIndex())
        {
            case 0:
                modelo.addElement("Sencilla $1200");
                modelo.addElement("Doble $2100");
                modelo.addElement("Suite $3500");
                jlsHabitacion.setModel(modelo);
            break;
            case 1:
                modelo.addElement("Sencilla $1200");
                modelo.addElement("Doble $2100");
                modelo.addElement("Suite $3500");
                jlsHabitacion.setModel(modelo);
            break;
            case 2:
                modelo.addElement("Sencilla $3,000");
                modelo.addElement("Doble $4,000");
                modelo.addElement("Suite $6,000");
                jlsHabitacion.setModel(modelo);
            break;
            case 3:
                modelo.addElement("Sencilla $3,000");
                modelo.addElement("Doble $4,000");
                modelo.addElement("Suite $6,000");
                jlsHabitacion.setModel(modelo);
            break;
            case 4:
                modelo.addElement("Sencilla $5,000");
                modelo.addElement("Doble $8,000");
                modelo.addElement("Suite $12,000");
                jlsHabitacion.setModel(modelo);
            break;
        }
    }//GEN-LAST:event_jcbDestinoTuristicoActionPerformed

    private void jbnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnRegistrarActionPerformed
        //Agregar informacion a la lista de destinos
        lista.agregar(null,jcbDestinoTuristico.getSelectedItem().toString(), jlsHabitacion.getSelectedValue().toString(), 
                 null, null, null, null, null);
    }//GEN-LAST:event_jbnRegistrarActionPerformed

    private void jcbTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTarjetaActionPerformed
      /*  if(jcbTarjeta.isSelected())
        {
            
            jcbMensualidad.setSelected(false);
            lista
        }
        
         if(jcbPublico.isSelected())
        {
            cientifico.setInteres("Publico");
        }*/
    }//GEN-LAST:event_jcbTarjetaActionPerformed

    private void jbnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnMostrarActionPerformed
        if(lista.estaVacia())
        {
                    //Llamamos la ventana de mostrar y pasamos la infotmacion del objeto
            //frmVizualizarCotizacion abrir = new frmVizualizarCotizacion(lista , this);
           // abrir.setVisible(true); //Muestra la ventana de Registro
            this.setVisible(false);//Hace invisible la ventana actual
        }
        
    }//GEN-LAST:event_jbnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCotizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCotizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCotizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCotizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCotizador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbnLimpiar;
    private javax.swing.JButton jbnMostrar;
    private javax.swing.JButton jbnRegistrar;
    private javax.swing.JButton jbnRegresar;
    private javax.swing.JComboBox jcbDestinoTuristico;
    private javax.swing.JCheckBox jcbMensualidad;
    private javax.swing.JCheckBox jcbTarjeta;
    private javax.swing.JList jlsHabitacion;
    private javax.swing.JTextField jtfCantidadDias;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        
        
        
        jtfCantidadDias.requestFocus();
    }
}
